### ISSUE TITLE
[Android] Crash on start

### ISSUE THREAD

**Issue by ODINA101** [jesster2k10/react-native-bubble-select#1]
those are logs from logcat

 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Landroid/graphics/drawable/Drawable;ZLjava/lang/Integer;Lcom/igalata/bubblepicker/model/BubbleGradient;FLandroid/graphics/Typeface;Ljava/lang/Integer;FLandroid/graphics/drawable/Drawable;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/igalata/bubblepicker/model/PickerItem; or its super classes (declaration of 'com.igalata.bubblepicker.model.PickerItem' appears in /data/app/com.itravel-mgidcbCy7FHi2f1SBUjTyg==/base.apk!classes3.dex)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.reactnativebubbleselect.BubbleSelectView$setupBubblePickerAdapter$1.getItem(BubbleSelectView.kt:32)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.igalata.bubblepicker.rendering.BubblePicker.setAdapter(BubblePicker.kt:37)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.reactnativebubbleselect.BubbleSelectView.setupBubblePickerAdapter(BubbleSelectView.kt:28)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.reactnativebubbleselect.BubbleSelectView.addNode(BubbleSelectView.kt:56)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.reactnativebubbleselect.BubbleSelectViewManager.addView(BubbleSelectViewManager.kt:36)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.reactnativebubbleselect.BubbleSelectViewManager.addView(BubbleSelectViewManager.kt:9)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:512)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:205)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:721)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-02 16:58:03.434  8026  8026 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-02 16:58:03.440  1995  2753 W ActivityTaskManager:   Force finishing activity com.itravel/.MainActivity
04-02 16:58:03.444  1995  2753 W InputReader: Device has associated, but no associated display id.

**Comment by jesster2k10** [comment]
Android support at this moment is experimental, however it should be working. I think the best thing you could do is to create a public repo with the code you ran so I can try it out and see the issue.

Could you let me know what device you were running this on?

**Comment by ODINA101** [comment]
i use Pixel_3_API_29

**Comment by jesster2k10** [comment]
Do you have a sample repository I could check out?

**Comment by ODINA101** [comment]
@jesster2k10  sorry for late answer 

`import React from 'react';
import BubbleSelect, {Bubble} from 'react-native-bubble-select';
import {Dimensions, View} from 'react-native';

const {width, height} = Dimensions.get('window');

export default class Anime extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: [
        {name: 'test1'},
        {name: 'test2'},
        {name: 'test3'},
        {name: 'test4'},
        {name: 'test5'},
      ],
    };

    setInterval(() => {
      let dt = this.state.data;
      dt.push({name: 'test'});
      this.setState({data: dt});
    }, 5000);
  }
  render() {
    return (
      <BubbleSelect
        autoSize
        style={{backgroundColor: 'transparent'}}
        color="blue"
        onSelect={bubble => console.log('Selected: ', bubble.id)}
        onDeselect={bubble => console.log('Deselected: ', bubble.id)}
        width={width}
        height={height}>
        {this.state.data.map((item, ind) => {
          return (
            <Bubble autoSize key={ind} id={'bubble-' + ind} text={item.name} />
          );
        })}
      </BubbleSelect>
    );
  }
}
`

**Comment by ODINA101** [comment]
this is my code ios works and android crash
