### ISSUE TITLE
Change magnetic settings?

### ISSUE THREAD

**Issue by eurobob** [jesster2k10/react-native-bubble-select#10]
Would it be possible to have bubbles float to the top of the view instead of towards the middle?

I effectively want to do a vertical scrolling list of bubbles instead of the current layout.

**Comment by jesster2k10** [comment]
I don't think that's possible without changing the underlying physics in the native libraries. You could open an issue in either [Magnetic](https://github.com/efremidze/Magnetic) or [Bubble-Picker](https://github.com/igalata/Bubble-Picker) for android
