### ISSUE TITLE
[iOS] Bubbles partially showing

### ISSUE THREAD

**Issue by Wallow17** [jesster2k10/react-native-bubble-select#2]
Hi **jesster2k10**, First I would to thank you for your work.

Unfortunately I have a little problem with the display, I have an array of 7 items but only half are displayed.

Here is my code, I hope you can help me
Logan.

![Simulator Screen Shot - iPhone 11 - 2020-04-04 at 17 16 31](https://user-images.githubusercontent.com/36372368/78454553-fb36ca80-7698-11ea-821a-3910e7a370e2.png)

import React, {useState} from 'react';
import RegisterLayout from '../components/RegisterLayout';
import SpookyButton from '../components/SpookyButton';
import BubbleSelect, {Bubble} from 'react-native-bubble-select';
import colors from '../styles/colors';
import {View} from 'react-native';

const interestsHelper = [
  'Jazz',
  'Tennis',
  'Foot',
  'Rap',
  'Art',
  'Design',
  'Cinéma',
];

function RegisterInterests() {
  const [interests, setInterests] = useState([]);
  return (
    <RegisterLayout canGoBack={true}>
      <View style={{flex: 1}}>
        <BubbleSelect
          onSelect={bubble =>
            // @ts-ignore
            setInterests([...interests, parseInt(bubble.id, 10)])
          }
          onDeselect={bubble =>
            setInterests(interests.filter(b => b !== parseInt(bubble.id, 10)))
          }
          // @ts-ignore
          width={'100%'}>
          {interestsHelper.map((bubble, bubbleIndex) => {
            return (
              <Bubble
                id={bubbleIndex.toString()}
                text={bubble}
                color={'transparent'}
                selectedColor={colors.blue}
                borderColor={colors.blue}
                borderWidth={1}
                fontColor={colors.blue}
                selectedFontColor={'white'}
                fontName={'San Francisco'}
              />
            );
          })}
        </BubbleSelect>
      </View>
      <SpookyButton title={'Terminer'} disabled={interests.length === 0} />
    </RegisterLayout>
  );
}

export default RegisterInterests;

PS: I did not manage to change the background color with a "style" prop

**Comment by jesster2k10** [comment]
Hey there, this is actually a known issue in iOS. It's to do with the actual library the project is based on, there is an open issue there which is yet to be resolved.

From my testing, this issue could be rectified by storing the dynamically shown items in the state, and setting them in the state on mount forcing a re-render.

So the solution to this would be like so:

```js
const interestsHelper = [
  'Jazz',
  'Tennis',
  'Foot',
  'Rap',
  'Art',
  'Design',
  'Cinéma',
];

const RegisterInterests = () => {
  const [interests, setInterests] = useState([])

  useEffect(() => {
    setInterests(interestsHelper)
  }, [])

  // use the interests from the state opposed to interest helper..
}
```

That should hopefully do the trick on this version `0.5.0`. The issue should be rectified in the next release. 

If that works for you, let me know.

**Comment by jesster2k10** [comment]
Also, as of now there's no way to change the background from the default `white`.
I can add that feature an make a small update within the next hour or so, it's a minor change.

**Comment by Wallow17** [comment]
It works! Thank you again, and thanks for the backgroundColor feature

**Comment by jesster2k10** [comment]
No problem, it should be worth nothing that this hack is only needed for iOS so you might want to use `Platform.OS` and do like so to prevent the needless re-render on android:

```jsx
React.useEffect(() => {
    if (force) {
      setCities(randomCities());
    }
  }, [force]);

  React.useEffect(() => {
    if (Platform.OS === 'ios') {
      setForce(true);
    } else {
      setCities(randomCities());
    }
  }, []);
```

**Comment by rutul089** [comment]
Hi @jesster2k10, Thank you for your work.

Unfortunately, this hack is not working for me half of the array is showing in iOS I am using same code mention above.
