### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by KrishEnacton** [jesster2k10/react-native-bubble-select#22]
BubbleSelectView.kt: (89, 62): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type UIManagerModule?

**Comment by jesster2k10** [comment]
@KrishEnacton Will take a look into it.

**Comment by Arslan106** [comment]
still getting this error

**Comment by pallaviMN** [comment]
@jesster2k10 , is it resolved?

**Comment by justinrubek** [comment]
> @jesster2k10 , is it resolved?

Sure doesn't look like it to me. Experiencing the same problem

**Comment by 3KINGZ** [comment]
still experiencing the same issue

**Comment by 3KINGZ** [comment]
> > @jesster2k10 , is it resolved?
> 
> Sure doesn't look like it to me. Experiencing the same problem
> 
> Edit: I've fixed the issue myself, I'll be submitting a PR soon

what's the solution?

**Comment by ombogdan** [comment]
same problem

**Comment by TheSirZS** [comment]
Any solution?
