### ISSUE TITLE
[iOS] main queue setup waring

### ISSUE THREAD

**Issue by eurobob** [jesster2k10/react-native-bubble-select#4]
> Module RNBubbleSelectNodeViewManager requires main queue setup since it overrides 'init'  but doesn't implement 'requiresMainQueueSetup'. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by jesster2k10** [comment]
Hey, this is a known issue with a relatively simple fix. I'll push some changes later on which will resolve that.

It's a minor issue and does not affect usage.

**Comment by eurobob** [comment]
Yeah, no worries. I was getting annoyed by the yellowbox in dev so I submitted a pull request #5

**Comment by jesster2k10** [comment]
> Yeah, no worries. I was getting annoyed by the yellowbox in dev so I submitted a pull request #5

Thank you for that, I'll check it out and review it now
