### ISSUE TITLE
requireNativeComponent: "RNBubbleSelectNodeView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Zinyon** [jesster2k10/react-native-bubble-select#9]
Hello, Thanks for your sharing library at first.
I'm using expo on Android phone and I just got an error.
Is there a problem with using expo?

![image](https://user-images.githubusercontent.com/26531678/86564598-74e49a00-bfa1-11ea-93ed-51a3b431ea75.png)

**Comment by i-Rony** [comment]
Facing the Same Issue, is there a way out?

**Comment by Zinyon** [comment]
@i-Rony 
It's because of expo .
expo could not offer third-party-native-component.

I've solved it by changing environment (expo -> react-native-cli).

**Comment by thechaudharysab** [comment]
@jesster2k10 I'm using `react-native-cli` but I am getting the same error on Android.
